<#
.SYNOPSIS
Creates one Excel-sourced Defender AV exclusions policy per platform: Windows, macOS, Linux.

.DESCRIPTION
Uses the temporary app registration created by New-MdeXdrGraphUploadApp.ps1 and the Excel-only output
files generated by New-MdeXdrDefenderAvExclusionFiles.ps1. Windows paths are packed into one pipe-
delimited Defender CSP value so Windows can be represented by one policy object.
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$AppPrivatePath = ".\out\mde-xdr-upload-app-private.json",
    [string]$OutDir = ".\out",
    [ValidateSet("USGov")]
    [string]$Cloud = "USGov",
    [switch]$SkipExisting
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$graphHost = "https://graph.microsoft.us"
$loginHost = "https://login.microsoftonline.us"

if (-not (Test-Path $AppPrivatePath)) { throw "App private file not found: $AppPrivatePath" }
$app = Get-Content $AppPrivatePath -Raw | ConvertFrom-Json
$token = Invoke-RestMethod -Method POST -Uri "$loginHost/$($app.TenantId)/oauth2/v2.0/token" -Body @{
    client_id = $app.ClientId
    client_secret = $app.ClientSecret
    scope = "$graphHost/.default"
    grant_type = "client_credentials"
}
$headers = @{ Authorization = "Bearer $($token.access_token)" }

function Invoke-LocalGraphRequest {
    param(
        [ValidateSet("GET", "POST", "DELETE")]
        [string]$Method,
        [string]$Uri,
        $Body
    )

    if ($PSBoundParameters.ContainsKey("Body")) {
        return Invoke-RestMethod -Method $Method -Uri $Uri -Headers $headers -Body ($Body | ConvertTo-Json -Depth 100) -ContentType "application/json"
    }
    return Invoke-RestMethod -Method $Method -Uri $Uri -Headers $headers
}

function Get-PipeValues {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return @() }
    $raw = Get-Content $Path -Raw
    if ([string]::IsNullOrWhiteSpace($raw)) { return @() }
    return @($raw -split "\|" | ForEach-Object { $_.Trim() } | Where-Object { $_ })
}

function New-TemplateReference {
    param([string]$Id)
    [ordered]@{ settingInstanceTemplateId = $Id }
}

function New-ValueTemplateReference {
    param([string]$Id)
    [ordered]@{ settingValueTemplateId = $Id; useTemplateDefault = $false }
}

function New-StringSettingValue {
    param([string]$Value)
    [ordered]@{
        "@odata.type" = "#microsoft.graph.deviceManagementConfigurationStringSettingValue"
        value = $Value
    }
}

function New-ChoiceSettingValue {
    param(
        [string]$Value,
        [string]$ValueTemplateId,
        [object[]]$Children = @()
    )
    [ordered]@{
        "@odata.type" = "#microsoft.graph.deviceManagementConfigurationChoiceSettingValue"
        value = $Value
        children = @($Children)
    }
}

function New-SimpleChildInstance {
    param(
        [string]$DefinitionId,
        [string]$Value
    )
    [ordered]@{
        "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSimpleSettingInstance"
        settingDefinitionId = $DefinitionId
        simpleSettingValue = New-StringSettingValue -Value $Value
    }
}

function New-ChoiceChildInstance {
    param(
        [string]$DefinitionId,
        [string]$Value,
        [object[]]$Children = @()
    )
    [ordered]@{
        "@odata.type" = "#microsoft.graph.deviceManagementConfigurationChoiceSettingInstance"
        settingDefinitionId = $DefinitionId
        choiceSettingValue = [ordered]@{
            "@odata.type" = "#microsoft.graph.deviceManagementConfigurationChoiceSettingValue"
            value = $Value
            children = @($Children)
        }
    }
}

function New-WindowsPayload {
    $paths = Get-PipeValues -Path (Join-Path $OutDir "mde-xdr-windows-excel-master-defender-av-exclusion-paths.txt")
    $extensions = Get-PipeValues -Path (Join-Path $OutDir "mde-xdr-windows-excel-master-defender-av-exclusion-extensions.txt")
    $packedPaths = $paths -join "|"

    $settings = @(
        [ordered]@{
            "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSetting"
            settingInstance = [ordered]@{
                "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSimpleSettingCollectionInstance"
                settingDefinitionId = "device_vendor_msft_policy_config_defender_excludedpaths"
                settingInstanceTemplateReference = New-TemplateReference -Id "aaf04adc-c639-464f-b4a7-152e784092e8"
                simpleSettingCollectionValue = @(New-StringSettingValue -Value $packedPaths)
            }
        },
        [ordered]@{
            "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSetting"
            settingInstance = [ordered]@{
                "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSimpleSettingCollectionInstance"
                settingDefinitionId = "device_vendor_msft_policy_config_defender_excludedextensions"
                settingInstanceTemplateReference = New-TemplateReference -Id "c203725b-17dc-427b-9470-673a2ce9cd5e"
                simpleSettingCollectionValue = @($extensions | ForEach-Object { New-StringSettingValue -Value $_ })
            }
        }
    )

    New-PolicyPayload -Name "MDE AV Exclusions - Windows" -Description "Excel-sourced Windows Defender AV exclusions. Paths packed as one pipe-delimited Defender CSP value." -Platform "windows10" -Technology "microsoftSense" -TemplateId "45fea5e9-280d-4da1-9792-fb5736da0ca9_1" -Settings $settings
}

function New-GroupExclusionValue {
    param(
        [string]$RootPrefix,
        [string]$Type,
        [string]$Value,
        [hashtable]$Template
    )

    $isPath = $Type -eq "Path"
    $isExtension = $Type -eq "Extension"
    $isProcess = $Type -eq "Process"

    $typeOption = if ($isPath) { "$($RootPrefix)_item_`$type_0" } elseif ($isExtension) { "$($RootPrefix)_item_`$type_1" } else { "$($RootPrefix)_item_`$type_2" }
    $groupValueTemplateId = if ($isPath) { $Template.PathGroupValueTemplateId } elseif ($isExtension) { $Template.ExtensionGroupValueTemplateId } else { $Template.ProcessGroupValueTemplateId }
    $typeInstanceTemplateId = if ($isPath) { $Template.PathTypeInstanceTemplateId } elseif ($isExtension) { $Template.ExtensionTypeInstanceTemplateId } else { $Template.ProcessTypeInstanceTemplateId }
    $typeValueTemplateId = if ($isPath) { $Template.PathTypeValueTemplateId } elseif ($isExtension) { $Template.ExtensionTypeValueTemplateId } else { $Template.ProcessTypeValueTemplateId }

    $children = @()
    if ($isPath) {
        $children += New-SimpleChildInstance -DefinitionId "$($RootPrefix)_item_path" -Value $Value
        $children += New-ChoiceChildInstance -DefinitionId "$($RootPrefix)_item_isdirectory" -Value "$($RootPrefix)_item_isdirectory_true"
    }
    elseif ($isExtension) {
        $children += New-SimpleChildInstance -DefinitionId "$($RootPrefix)_item_extension" -Value $Value
    }
    elseif ($isProcess) {
        $children += New-SimpleChildInstance -DefinitionId "$($RootPrefix)_item_name" -Value $Value
    }

    [ordered]@{
        "@odata.type" = "#microsoft.graph.deviceManagementConfigurationGroupSettingValue"
        children = @(
            [ordered]@{
                "@odata.type" = "#microsoft.graph.deviceManagementConfigurationChoiceSettingInstance"
                settingDefinitionId = "$($RootPrefix)_item_`$type"
                choiceSettingValue = New-ChoiceSettingValue -Value $typeOption -ValueTemplateId $typeValueTemplateId -Children $children
            }
        )
    }
}

function New-GroupedPayload {
    param(
        [string]$Name,
        [string]$Prefix,
        [string]$Platform,
        [string]$Technology,
        [string]$TemplateId,
        [string]$RootDefinitionId,
        [string]$RootPrefix,
        [hashtable]$Template
    )

    $paths = Get-PipeValues -Path (Join-Path $OutDir "$Prefix-defender-av-exclusion-paths.txt")
    $processes = Get-PipeValues -Path (Join-Path $OutDir "$Prefix-defender-av-exclusion-processes.txt")
    $extensions = Get-PipeValues -Path (Join-Path $OutDir "$Prefix-defender-av-exclusion-extensions.txt")

    $values = @()
    $values += @($paths | ForEach-Object { New-GroupExclusionValue -RootPrefix $RootPrefix -Type "Path" -Value $_ -Template $Template })
    $values += @($extensions | ForEach-Object { New-GroupExclusionValue -RootPrefix $RootPrefix -Type "Extension" -Value $_ -Template $Template })
    $values += @($processes | ForEach-Object { New-GroupExclusionValue -RootPrefix $RootPrefix -Type "Process" -Value $_ -Template $Template })

    $settings = @(
        [ordered]@{
            "@odata.type" = "#microsoft.graph.deviceManagementConfigurationSetting"
            settingInstance = [ordered]@{
                "@odata.type" = "#microsoft.graph.deviceManagementConfigurationGroupSettingCollectionInstance"
                settingDefinitionId = $RootDefinitionId
                settingInstanceTemplateReference = New-TemplateReference -Id $Template.RootInstanceTemplateId
                groupSettingCollectionValue = @($values)
            }
        }
    )

    New-PolicyPayload -Name $Name -Description "Excel-sourced $Name Defender AV exclusions." -Platform $Platform -Technology $Technology -TemplateId $TemplateId -Settings $settings
}

function New-PolicyPayload {
    param(
        [string]$Name,
        [string]$Description,
        [string]$Platform,
        [string]$Technology,
        [string]$TemplateId,
        [object[]]$Settings
    )
    [ordered]@{
        name = $Name
        description = $Description
        platforms = $Platform
        technologies = $Technology
        roleScopeTagIds = @("0")
        templateReference = [ordered]@{
            templateId = $TemplateId
            templateFamily = "endpointSecurityAntivirus"
        }
        settings = @($Settings)
        assignments = @()
    }
}

function Publish-Policy {
    param([object]$Payload)

    $payloadPath = Join-Path $OutDir ("final-policy-{0}.json" -f (($Payload.name -replace '[^a-zA-Z0-9]+','-').Trim('-').ToLowerInvariant()))
    $Payload | ConvertTo-Json -Depth 100 | Set-Content -Path $payloadPath -Encoding UTF8 -WhatIf:$false

    $existingUri = "$graphHost/beta/deviceManagement/configurationPolicies?`$filter=name eq '$($Payload.name.Replace("'", "''"))'"
    $existing = Invoke-LocalGraphRequest -Method GET -Uri $existingUri
    if (@($existing.value).Count -gt 0) {
        if ($SkipExisting) {
            $policy = @($existing.value | Select-Object -First 1)
            return [pscustomobject]@{ Name = $policy.name; Id = $policy.id; Status = "SkippedExisting"; Payload = $payloadPath }
        }
        throw "Policy already exists: $($Payload.name). Use -SkipExisting or delete/rename it."
    }

    if ($PSCmdlet.ShouldProcess($Payload.name, "Create unassigned platform AV exclusions policy")) {
        $created = Invoke-LocalGraphRequest -Method POST -Uri "$graphHost/beta/deviceManagement/configurationPolicies" -Body $Payload
        return [pscustomobject]@{ Name = $created.name; Id = $created.id; Status = "Created"; Payload = $payloadPath }
    }

    [pscustomobject]@{ Name = $Payload.name; Id = "WHATIF"; Status = "WhatIf"; Payload = $payloadPath }
}

$macTemplate = @{
    RootInstanceTemplateId = "16162b31-076e-43b6-9e35-3d1f4a248eee"
    PathGroupValueTemplateId = "91002deb-82f4-44be-83e0-fcd729d7c873"
    ExtensionGroupValueTemplateId = "2a5c88ba-0167-433c-9712-6a8450726d1c"
    ProcessGroupValueTemplateId = "8b7c407b-a07a-44f6-8c2e-679bebe3a274"
    PathTypeInstanceTemplateId = "c82b1199-193b-45aa-bdfe-0d38a9001e82"
    ExtensionTypeInstanceTemplateId = "f30186fc-2254-4911-9111-d9028885bcba"
    ProcessTypeInstanceTemplateId = "03b2d4e8-eb88-4e76-b7eb-bfa9ebf1f4eb"
    PathTypeValueTemplateId = "239ca1ae-4a48-472d-bb21-055da52a357a"
    ExtensionTypeValueTemplateId = "f1c063e4-da8e-42b4-9207-205b6633a24c"
    ProcessTypeValueTemplateId = "6c6c508d-0dda-465f-81ae-678452c0bc27"
}

$linuxTemplate = @{
    RootInstanceTemplateId = "19436ea0-e842-4e29-861a-d8b781e1dcb5"
    PathGroupValueTemplateId = "35045835-a310-4a48-a31f-dccd9e50045b"
    ExtensionGroupValueTemplateId = "0fdc6a19-7c5d-4260-882e-d0dab015a814"
    ProcessGroupValueTemplateId = "fa0317dd-2cdb-4768-a877-85e99f12ad08"
    PathTypeInstanceTemplateId = "08bb2b44-765c-4005-a196-9d130b690190"
    ExtensionTypeInstanceTemplateId = "c1a735f4-e7d8-49b9-8ef0-3c5170b26cbb"
    ProcessTypeInstanceTemplateId = "9966c16f-8dc4-40d6-9c90-e22bb7365ec7"
    PathTypeValueTemplateId = "acd7aa70-58af-4c3c-95d9-e2d5509acac2"
    ExtensionTypeValueTemplateId = "195059b8-e9a8-4e21-90ff-66890c879750"
    ProcessTypeValueTemplateId = "ce1dd14b-c427-4bba-9752-d1028aef9d36"
}

$payloads = @(
    New-WindowsPayload
    New-GroupedPayload -Name "MDE AV Exclusions - macOS" -Prefix "mde-xdr-macos" -Platform "macOS" -Technology "microsoftSense" -TemplateId "43397174-2244-4006-b5ad-421b369e90d4_1" -RootDefinitionId "com.apple.managedclient.preferences_exclusions" -RootPrefix "com.apple.managedclient.preferences_exclusions" -Template $macTemplate
    New-GroupedPayload -Name "MDE AV Exclusions - Linux" -Prefix "mde-xdr-linux" -Platform "linux" -Technology "microsoftSense" -TemplateId "8a17a1e5-3df4-4e07-9d20-3878267a79b8_1" -RootDefinitionId "linux_mdatp_managed_antivirusengine_exclusions" -RootPrefix "linux_mdatp_managed_antivirusengine_exclusions" -Template $linuxTemplate
)

$results = foreach ($payload in $payloads) { Publish-Policy -Payload $payload }
$results | Format-Table -AutoSize